wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.9.1
    start_time: 1665654584
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 13
      4: 3.9.1
      5: 0.12.21
      8:
      - 1
      - 2
      - 5
    viz:
      class_proportions:
        historyFieldSettings:
          key: class_proportions
          x-axis: _step
        id: wandb/class_proportions/v1
      learning_curve:
        historyFieldSettings:
          key: learning_curve
          x-axis: _step
        id: wandb/learning_curve/v1
